# Cargo Makefile

# This env variable is need by cargo-make to enable correct functionality of commands
# in the context of a rust workspace: https://github.com/sagiegurari/cargo-make?tab=readme-ov-file#usage
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

# -- linting --------------------------------------------------------------------------------------
[tasks.clippy]
description = "Runs Clippy"
command = "cargo"
args = ["clippy", "--workspace", "--all-targets", "--all-features", "--", "-D", "warnings"]

[tasks.fix]
description = "Runs Fix"
command = "cargo"
toolchain = "nightly"
args = ["fix", "--allow-staged", "--allow-dirty", "--all-targets", "--all-features"]

[tasks.format]
description = "Runs Rustfmt"
command = "cargo"
toolchain = "nightly"
args = ["fmt"]

[tasks.lint]
description = "Runs all linting tasks (Clippy, fixing, formatting)"
dependencies = [
  "fix",
  "format",
  "clippy"
]

# --- docs ----------------------------------------------------------------------------------------
[tasks.doc]
env = { "RUSTDOCFLAGS" = "-D warnings" }
command = "cargo"
args = ["doc", "--all-features", "--keep-going", "--release"]

[tasks.doc-serve]
workspace = false
script = [ "./scripts/serve-doc-site.sh" ]

# --- testing -------------------------------------------------------------------------------------
[tasks.test]
disabled = true

[tasks.test-default]
description = "Run default tests excluding `prove`"
workspace = false
env = { "RUSTFLAGS" = "-C debug-assertions" }
command = "cargo"
args = ["nextest", "run", "--profile", "default", "--cargo-profile", "test-release", "--features", "concurrent,testing", "--filter-expr", "not test(prove)"]

[tasks.test-prove]
description = "Run `prove` tests (tests which use the Miden prover)"
workspace = false
env = { "RUSTFLAGS" = "-C debug-assertions" }
command = "cargo"
args = ["nextest", "run", "--profile", "prove", "--cargo-profile", "test-release", "--features", "concurrent,testing", "--filter-expr", "test(prove)"]

[tasks.test-all]
description = "Run all tests"
workspace = false
env = { "RUSTFLAGS" = "-C debug-assertions" }
run_task = { name = ["test-default", "test-prove"], parallel = true }

[tasks.ci-test-default]
description = "Run default tests excluding `prove`"
workspace = false
command = "cargo"
args = ["nextest", "run", "--profile", "ci-default", "--cargo-profile", "test-release", "--features", "concurrent,testing", "--filter-expr", "not test(prove)"]

[tasks.ci-test-prove]
description = "Run `prove` tests (tests which use the Miden prover)"
workspace = false
command = "cargo"
args = ["nextest", "run", "--profile", "ci-prove", "--cargo-profile", "test-release", "--features", "concurrent,testing", "--filter-expr", "test(prove)"]

[tasks.ci-test-all]
description = "Run all tests"
workspace = false
env = { "RUSTFLAGS" = "-C debug-assertions" }
run_task = { name = ["nextest-default", "nextest-prove"], parallel = true }

# --- building ------------------------------------------------------------------------------------
[tasks.build]
description = "Build in release mode"
command = "cargo"
args = ["build", "--release"]

[tasks.build-no-std]
description = "Build using no-std"
command = "cargo"
args = ["build", "--no-default-features", "--target", "wasm32-unknown-unknown", "--workspace", "--exclude", "miden-mock"]

# --- benchmarking --------------------------------------------------------------------------------
[tasks.bench-all]
description = "Run all available transaction benchmarks"
workspace = false
command = "cargo"
args = ["run", "--bin", "benchmarks", "--features", "executable", "all"]

[tasks.bench-tx]
description = "Run the transaction benchmark with default transaction script and notes"
workspace = false
command = "cargo"
args = ["run", "--bin", "benchmarks", "--features", "executable", "simple"]

[tasks.bench-p2id]
description = "Run the transaction benchmark which consumes a P2ID note into a basic wallet"
workspace = false
command = "cargo"
args = ["run", "--bin", "benchmarks", "--features", "executable", "p2id"]

# --- utilities -----------------------------------------------------------------------------------
[tasks.watch]
description = "Watch for changes and rebuild"
workspace = false
command = "cargo"
args = ["watch", "-w", "miden-lib/asm", "-x", "build"]
