# Runs linting related jobs.

name: lint

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  version:
    name: check rust version consistency
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - name: check rust versions
        run: ./scripts/check-rust-version.sh

  rustfmt:
    name: rustfmt nightly on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: davidB/rust-cargo-make@v1
      - name: cargo make - format
        run: cargo make format

  clippy:
    name: clippy stable on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: davidB/rust-cargo-make@v1
      - name: cargo make - clippy
        run: cargo make clippy
