# Runs no-std related jobs.

name: no-std

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  no-std:
    name: build ${{matrix.toolchain}} no-std for wasm32-unknown-unknown
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, nightly]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup target add wasm32-unknown-unknown
      - uses: davidB/rust-cargo-make@v1
      - name: cargo make - build-no-std
        run: cargo make build-no-std
