name: test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    name: test ${{matrix.toolchain}} on ${{matrix.os}} with ${{matrix.args}}
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, nightly]
        os: [ubuntu]
        args: ["default", "prove"]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
      - uses: dtolnay/rust-toolchain@stable
      - uses: davidB/rust-cargo-make@v1
      - uses: taiki-e/install-action@nextest
      - name: cargo make - test
        run: cargo make ci-test-${{matrix.args}}
